# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 18 Apr 2007 12:30:18 -0400
*               @ALL          1
*               @user         8
*               @admin      255
