# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon,  2 Apr 2007 23:51:52 -0400
*               @user         8
*               @admin      255
*	@ALL	1
