<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: ralucam
 * Date: Tue,  3 Apr 2007 20:11:29 -0400
 */

$conf['title'] = 'Spam Project';
$conf['start'] = 'spam';
$conf['allowdebug'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['rss_type'] = 'rss2';

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content
