# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun,  8 Apr 2007 23:20:08 -0400
*               @ALL          1
*               @user         8
*               @admin      255
