# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 10 Apr 2007 20:39:32 -0400
*               @ALL          1
*               @user         8
*               @admin      255
