<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: gabe
 * Date: Thu, 19 Apr 2007 00:57:44 -0400
 */

$conf['title'] = 'Web Application Privacy Protector';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['mailguard'] = 'visible';
$conf['htmlok'] = 1;
$conf['updatecheck'] = 0;

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content
