# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 19 Apr 2007 19:35:21 -0400
*               @ALL          1
*               @user         8
*               @admin      255
