<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: bduddie
 * Date: Thu, 19 Apr 2007 19:55:31 -0400
 */

$conf['title'] = 'dynamic load balancer';
$conf['start'] = 'dlb';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['phpok'] = 1;

@include(DOKU_CONF.'local.protected.php');

// end auto-generated content
